pages:
  image: node:16
  script:
    - npm install
    - npm run build -- --base=/assignment-2-trivia
    - rm -r public
    - mv dist public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - main

